//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.CTMuonSaches = new HashSet<CTMuonSach>();
            this.CTTraSaches = new HashSet<CTTraSach>();
        }
    
        public int Ma { get; set; }
        public string Ten { get; set; }
        public int MaLS { get; set; }
        public int SoLuong { get; set; }
        public string TenTG { get; set; }
        public Nullable<int> NamXB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTMuonSach> CTMuonSaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTraSach> CTTraSaches { get; set; }
        public virtual LoaiSach LoaiSach { get; set; }
    }
}
