//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TraSach()
        {
            this.CTTraSaches = new HashSet<CTTraSach>();
        }
    
        public int Ma { get; set; }
        public string MaTT { get; set; }
        public Nullable<int> MaSV { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTraSach> CTTraSaches { get; set; }
        public virtual SinhVien SinhVien { get; set; }
        public virtual ThuThu ThuThu { get; set; }
    }
}
